### ISSUE TITLE
Docker Installation

### ISSUE THREAD

**Issue by mathewjpotter** [m600x/cosmo-installer#1]
Im not sure what i'm doing wrong, but everytime i install arm docker it crashes and wont boot again

**Comment by m600x** [comment]
The installer is supposed to be run on an other device such as your laptop and not from the Cosmo.

On your cosmo:
- Do the initial installation
- Get the IP of your cosmo

On your laptop:
- Install docker
- Pull the repo
- Edit the `cosmo.yml` file following the readme guide
- Run `./start.sh`

The script will start a container with ansible that launch the installation process on the Cosmo IP set in the `cosmo.yml` file under the name `ansible_host`

**Comment by mathewjpotter** [comment]
duh... nice that worked great. all installed, but i have an issue after a reboot it appears to not boot again, checking keyboard layouts etc

**Comment by m600x** [comment]
Restart over and disable some module from `tasks/main.yml` by commenting out the `include` lines using `#` so you can pin point which one cause you trouble.
